runtime: go120
env_variables:
  STORAGE_BUCKET: bucket
  API_TOKEN: XXXXXXXXXX
  BIGQUERY_DATASET: dataset_id
  BIGQUERY_TABLE: table_id
  BIGQUERY_COLUMNS: field1,field2
  BLOCKS_URL: https://xxxxx.magellanic-clouds.net
  BLOCKS_API_TOKEN: xxxxxx

automatic_scaling:
  max_concurrent_requests: 24
